Repository d3/d3-array, pull requests merged in 2020-08, with the labels that each got.

#164 Fix ceil & floor.
  src/ticks.js
  test/ticks-test.js
Labels: bugfix

#155 document a typical threshold generator for date values
  README.md
Labels: documentation

#156 bisector.center
  README.md
  src/bisector.js
  test/bisect-test.js
  test/bisector-test.js
Labels: feature
